Remove nvhost-nvcsi-t194.o from ACK build
Including nvhost-nvcsi-t194.o in ACK build gives
the following errors :
ERROR: modpost: "tegra_csi_media_controller_remove" undefined!
ERROR: modpost: "tegra_csi_media_controller_init" undefined!
ERROR: modpost: "csi5_fops" undefined!

Bug 3974840

Change-Id: Iad263a8aa0cef443dd4629d52417e5d104baf9fa
Signed-off-by: Bruce Xu <brucex@nvidia.com>
(cherry picked from commit ef3dfca356c6d41ca6a9a590d0bec861aeb50b41)
Reviewed-on: https://git-master.nvidia.com/r/c/linux-nv-oot/+/2910055
Reviewed-by: svcacv <svcacv@nvidia.com>
Reviewed-by: Ankita Garg <ankitag@nvidia.com>
Reviewed-by: Laxman Dewangan <ldewangan@nvidia.com>
GVS: Gerrit_Virtual_Submit <buildbot_gerritrpt@nvidia.com>
Tested-by: Ankita Garg <ankitag@nvidia.com>