cpuidle: tegra: cpuidle-tegra-auto compilation fix
Fix the error on compiling cpuidle-tegra-auto as OOT module.
Keeping the change in a separate patch for better tracking the
changes done.

Issues resolved are:
 ERROR: modpost: "s2idle_state"
 Fix: used a local variable s2idle_sc7_state to fix

 ERROR: modpost: "__boot_cpu_id"
 Fix: Used CPU number "0" always. It's a logical number and we
      don't have a dependency on the actual boot CPU.

 ERROR: modpost: "cpuidle_devices"
 Fix: Used a per cpu variable "tegra_auto_cpuidle_drivers" of type
      "struct cpuidle_driver *" to store and fetch the "*drv".

Bug 3583597

Change-Id: Idf1c4f4eecbdd638e31e0b76efa140a8f45616e9
Signed-off-by: Sumit Gupta <sumitg@nvidia.com>
Reviewed-on: https://git-master.nvidia.com/r/c/linux-nv-oot/+/2843935
(cherry picked from commit a101f1bf1175f18744082f175f91a411903b9f45)
Reviewed-on: https://git-master.nvidia.com/r/c/linux-nv-oot/+/2819960
Reviewed-by: svcacv <svcacv@nvidia.com>
Reviewed-by: Sandeep Trasi <strasi@nvidia.com>
GVS: Gerrit_Virtual_Submit <buildbot_gerritrpt@nvidia.com>
Tested-by: Preetham Chandru <pchandru@nvidia.com>