drivers: bmi088: Only build bmi088 if CONFIG_IIO is set
If the bmi088 is built against a kernel that does not have CONFIG_IIO
enabled, then the build fails because the following symbols are not
found ...

 ERROR: modpost: "iio_read_const_attr" [drivers/bmi088/bmi088.ko]
  undefined!
 ERROR: modpost: "iio_kfifo_allocate" [drivers/bmi088/bmi088.ko]
  undefined!
 ERROR: modpost: "devm_iio_device_alloc" [drivers/bmi088/bmi088.ko]
  undefined!
 ERROR: modpost: "__devm_iio_device_register" [drivers/bmi088/bmi088.ko]
  undefined!
 ERROR: modpost: "iio_device_attach_buffer" [drivers/bmi088/bmi088.ko]
  undefined!
 ERROR: modpost: "iio_push_to_buffers" [drivers/bmi088/bmi088.ko]
  undefined!

Fix this by only building the bmi088 driver is CONFIG_IIO is enabled.

Bug 4190630

Change-Id: I9ca80d9a638d33d8996d5197b6f44f1d7382a9d2
Signed-off-by: Jon Hunter <jonathanh@nvidia.com>
Reviewed-on: https://git-master.nvidia.com/r/c/linux-nv-oot/+/2986513
Reviewed-by: Gautham Srinivasan <gauthams@nvidia.com>
GVS: Gerrit_Virtual_Submit <buildbot_gerritrpt@nvidia.com>