drm/tegra: Fix support for Linux v5.10
When compiling the Tegra DRM driver for Linux v5.10 it is currently
failing and the following errors are seen ...

 tegra/dc.c: In function 'tegra_crtc_atomic_begin':
 tegra/dc.c:2278:43: error: 'state' undeclared (first use in this function)
  tegra_crtc_update_memory_bandwidth(crtc, state, true);
                                             ^~~~~
 tegra/dc.c:2524:18: error: initialization from incompatible pointer type
 [-Werror=incompatible-pointer-types]
  .atomic_check = tegra_crtc_atomic_check,
                  ^~~~~~~~~~~~~~~~~~~~~~~

Upstream commit 04d5d5df9df7 ("drm/tegra: dc: Support memory bandwidth
management") added support for memory bandwidth and so disable this for
Linux kernel prior to v5.11 due to incompatibilty with these earlier
versions.

JIRA LS-410

Change-Id: Ic130a6e37cef597772b62be192f154a2681fe157
Signed-off-by: Jon Hunter <jonathanh@nvidia.com>
Reviewed-on: https://git-master.nvidia.com/r/c/linux-nvidia/+/2668675
Reviewed-by: Mikko Perttunen <mperttunen@nvidia.com>
Reviewed-by: svc_kernel_abi <svc_kernel_abi@nvidia.com>
GVS: Gerrit_Virtual_Submit