Remove tegra-camera.o from ACK build
Including tegra-camera.o in ACK build will lead to the
following errors :
ERROR: modpost: "v4l2_async_register_subdev" undefined!
ERROR: modpost: "v4l2_fwnode_put_link" undefined!
ERROR: modpost: "v4l2_async_notifier_init" undefined!
ERROR: modpost: "__v4l2_async_notifier_add_subdev" undefined!
ERROR: modpost: "v4l2_async_notifier_register" undefined!
ERROR: modpost: "v4l2_fwnode_parse_link" undefined!
ERROR: modpost: "vb2_dma_contig_set_max_seg_size" undefined!
ERROR: modpost: "v4l2_async_unregister_subdev" undefined!
ERROR: modpost: "v4l2_async_notifier_unregister" undefined!

Bug 3974840

Change-Id: Ia76a0e79efd495189d0de7053101bdfd3309fba8
Signed-off-by: Bruce Xu <brucex@nvidia.com>
(cherry picked from commit d53366444ca977e09622331aad1cb1913a8ceed0)
Reviewed-on: https://git-master.nvidia.com/r/c/linux-nv-oot/+/2909237
Tested-by: Ankita Garg <ankitag@nvidia.com>
Reviewed-by: Ankita Garg <ankitag@nvidia.com>
Reviewed-by: svcacv <svcacv@nvidia.com>
Reviewed-by: Laxman Dewangan <ldewangan@nvidia.com>
GVS: Gerrit_Virtual_Submit <buildbot_gerritrpt@nvidia.com>