ASoC: tegra: Fix build error for MODS
MODS build has 'CONFIG_TEGRA_ISOMGR' enabled and it is resulting in
following build errors.

 ERROR: modpost: "tegra_isomgr_register"
     [sound/soc/tegra/snd-soc-tegra-utils.ko] undefined!
 ERROR: modpost: "tegra_set_latency_allowance"
     [sound/soc/tegra/snd-soc-tegra-utils.ko] undefined!
 ERROR: modpost: "tegra_isomgr_realize"
     [sound/soc/tegra/snd-soc-tegra-utils.ko] undefined!
 ERROR: modpost: "tegra_isomgr_reserve"
     [sound/soc/tegra/snd-soc-tegra-utils.ko] undefined!
 ERROR: modpost: "tegra_isomgr_unregister"
     [sound/soc/tegra/snd-soc-tegra-utils.ko] undefined!

This happens because TEGRA_ISOMGR is not functionally up on v5.9.
Actually it has dependency over 'CONFIG_NV_TEGRA_MC' and thus build
issue is fixed by adding an explicit check for it. On L4T this issue
is not seen because 'CONFIG_TEGRA_ISOMGR' is not enabled.

Bug 200622929

Change-Id: Iceebf0df6e33386a5df06c5263a4a46b5bcd5d42
Signed-off-by: Sameer Pujar <spujar@nvidia.com>
Reviewed-on: https://git-master.nvidia.com/r/c/linux-5.9/+/2404198
Reviewed-by: automaticguardword <automaticguardword@nvidia.com>
Reviewed-by: Automatic_Commit_Validation_User
Reviewed-by: Rajesh Gumasta <rgumasta@nvidia.com>
Reviewed-by: Bitan Biswas <bbiswas@nvidia.com>
Reviewed-by: mobile promotions <svcmobile_promotions@nvidia.com>
GVS: Gerrit_Virtual_Submit
Tested-by: Rajesh Gumasta <rgumasta@nvidia.com>
Tested-by: mobile promotions <svcmobile_promotions@nvidia.com>