Remove nvhost-vi5.o from ACK build
Including nvhost-vi5.o in ACK build gives
the following errors :
ERROR: modpost: "vi_channel_drv_fops_register" undefined!
ERROR: modpost: "tegra_vi_media_controller_cleanup" undefined!
ERROR: modpost: "vi_channel_drv_unregister" undefined!

Bug 3974840

Change-Id: I85050b229eab88e60a02d244c95b9dad0a5b6851
Signed-off-by: Bruce Xu <brucex@nvidia.com>
(cherry picked from commit eea31fd3f7b941c124f210278d878b42f6edf469)
Reviewed-on: https://git-master.nvidia.com/r/c/linux-nv-oot/+/2910056
Reviewed-by: svcacv <svcacv@nvidia.com>
Reviewed-by: Ankita Garg <ankitag@nvidia.com>
Reviewed-by: Laxman Dewangan <ldewangan@nvidia.com>
GVS: Gerrit_Virtual_Submit <buildbot_gerritrpt@nvidia.com>
Tested-by: Ankita Garg <ankitag@nvidia.com>