drivers: nv-p2p: fix compilation error in Nvidia Tegra P2P driver
Fix compilation error on making Nvidia Tegra P2P Driver as OOT.
Error coming because the get_user_pages_locked() API is removed now.
 https://lore.kernel.org/all/20220204020010.68930-6-jhubbard@nvidia.com/T/#mebb2b2dd622f702e76120aeca7896a4fd184d5c1

 kernel-oot/kernel-nvidia-oot/nvidia-oot/drivers/nv-p2p/nvidia-p2p.c
 :169:43: error: implicit declaration of function
 _get_user_pages_locked_; did you mean _get_user_pages_unlocked_?
 [-Werror=implicit-function-declaration]
  169 | user_pages = safe_cast_s64_to_s32(get_user_pages_locked
        (vaddr & PAGE_MASK, nr_pages,
      |                                   ^~~~~~~~~~~~~~~~~~~~~
      |                                   get_user_pages_unlocked
 cc1: all warnings being treated as errors

Bug 4142533

Change-Id: Ic368ec288560f8f3c0acea29cfc935059ce2857e
Signed-off-by: Sumit Gupta <sumitg@nvidia.com>
Reviewed-on: https://git-master.nvidia.com/r/c/linux-nv-oot/+/2978104
Reviewed-by: Preetham Chandru <pchandru@nvidia.com>
Reviewed-by: Bibek Basu <bbasu@nvidia.com>
GVS: Gerrit_Virtual_Submit <buildbot_gerritrpt@nvidia.com>